.TH lb 1 "September 2005"  "Version 1.0.0" "1.0.0"
.SH NAME
lbgui \- GUI front end for lb
.SH DESCRIPTION


This is a GUI front-end for The Little Budgeting Tool (lb).  It has
the same command line arguments as lb.  The main difference is that is
starts up in a window and has semi-user-friendly buttons to use.

See 
.BR lb (1)
for a full description.

.SH "SEE ALSO"

.BR gnucash (1),
.BR lb (1)

.SH AUTHOR

G. M. Beddingfield <gabriel@teuton.org>
